export const getMockReviews = () => {
  return [
    {
      _id: 'mock1',
      rating: 5,
      title: 'Excellent Quality and Fit!',
      comment: 'Bohot hi badhiya fabric hai! I ordered this for my brother and the fit is absolutely perfect. The material is very breathable, especially good for Indian summers. Highly recommended!',
      user: { name: 'Rahul Sharma' },
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 45,
      dislikes: 2,
      location: 'New Delhi'
    },
    {
      _id: 'mock2',
      rating: 4,
      title: 'Value for Money',
      comment: 'Product exactly as shown in the picture. Color did not fade after the first wash. Packaging was decent and delivery was very fast. Good purchase from Zen-G Wear.',
      user: { name: 'Priya Patel' },
      createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 32,
      dislikes: 1,
      location: 'Mumbai'
    },
    {
      _id: 'mock3',
      rating: 5,
      title: 'Awesome Product 😍',
      comment: 'Just wow! I was a bit skeptical before ordering but the quality exceeded my expectations. The stitching is very premium. Flipkart Assured delivery was blazing fast.',
      user: { name: 'Amit Kumar' },
      createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 120,
      dislikes: 5,
      location: 'Bengaluru'
    },
    {
      _id: 'mock4',
      rating: 3,
      title: 'Good but size runs slightly small',
      comment: 'The cloth quality is top-notch, no doubt about it. But I ordered an L size and it feels a bit tight, more like an M. Suggest ordering one size larger for a comfortable fit.',
      user: { name: 'Vikram Singh' },
      createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 89,
      dislikes: 14,
      location: 'Jaipur'
    },
    {
      _id: 'mock5',
      rating: 5,
      title: 'Super comfortable!',
      comment: 'Ekdum mast! Fabric feels very soft against the skin. Wearing it daily for college and it still looks fresh. Zen-G Wear is becoming my favorite brand now.',
      user: { name: 'Neha Gupta' },
      createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 56,
      dislikes: 0,
      location: 'Pune'
    },
    {
      _id: 'mock6',
      rating: 4,
      title: 'Nice product, fast delivery',
      comment: 'Delivery boy was polite and delivered it within 2 days. The product is 100% genuine and looks great. Satisfied with the purchase.',
      user: { name: 'Anjali Verma' },
      createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 21,
      dislikes: 3,
      location: 'Lucknow'
    },
    {
      _id: 'mock7',
      rating: 5,
      title: 'Perfect for gifting',
      comment: 'Gifted this to my husband on his birthday. He loved it! The packaging was so premium, I did not even need to wrap it again. 5 stars to Zen-G Wear!',
      user: { name: 'Kavita Iyer' },
      createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 67,
      dislikes: 1,
      location: 'Chennai'
    },
    {
      _id: 'mock8',
      rating: 5,
      title: 'Mind-blowing purchase',
      comment: 'Bhaiyya, itne kam price mein itni achi quality kahin nahi milegi. Simply superb. I have ordered 3 more in different colors.',
      user: { name: 'Rohan Desai' },
      createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 154,
      dislikes: 8,
      location: 'Ahmedabad'
    },
    {
      _id: 'mock9',
      rating: 4,
      title: 'Worth every penny',
      comment: 'Good product. The color is slightly darker than the image, but still looks very stylish. Fabric is pure cotton.',
      user: { name: 'Suresh Menon' },
      createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 43,
      dislikes: 2,
      location: 'Kochi'
    },
    {
      _id: 'mock10',
      rating: 2,
      title: 'Delivery was late',
      comment: 'Product is decent but the courier partner took 7 days to deliver. Expected better service.',
      user: { name: 'Deepak Reddy' },
      createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 12,
      dislikes: 45,
      location: 'Hyderabad'
    },
    {
      _id: 'mock11',
      rating: 5,
      title: 'Excellent',
      comment: 'Very nice and comfortable. Perfect fitting and color is also very bright and looks awesome.',
      user: { name: 'Sunil Joshi' },
      createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 8,
      dislikes: 0,
      location: 'Bhopal'
    },
    {
      _id: 'mock12',
      rating: 5,
      title: 'Brilliant',
      comment: 'Must buy! Zen-G wear never disappoints. The material is thick but very comfortable.',
      user: { name: 'Manish Tiwari' },
      createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 29,
      dislikes: 1,
      location: 'Indore'
    },
    {
      _id: 'mock13',
      rating: 4,
      title: 'Good choice',
      comment: 'Satisfied with the product. Looks very premium and trendy. Go for it guys.',
      user: { name: 'Aakash Mehra' },
      createdAt: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 15,
      dislikes: 2,
      location: 'Gurgaon'
    },
    {
      _id: 'mock14',
      rating: 5,
      title: 'Beautiful design',
      comment: 'Exactly as shown in the pictures. The design and finish are very neat. Happy customer!',
      user: { name: 'Sneha Rao' },
      createdAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 77,
      dislikes: 4,
      location: 'Bangalore'
    },
    {
      _id: 'mock15',
      rating: 4,
      title: 'Very nice',
      comment: 'Fabric quality is good. It gives a very smart look. Delivered on time.',
      user: { name: 'Nikhil Agarwal' },
      createdAt: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 19,
      dislikes: 1,
      location: 'Kolkata'
    },
    {
      _id: 'mock16',
      rating: 5,
      title: 'Superb Quality',
      comment: 'I am writing this review after 2 months of heavy usage and multiple washes. The fabric is totally intact, no pilling or color loss.',
      user: { name: 'Karan Malhotra' },
      createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 201,
      dislikes: 12,
      location: 'Chandigarh'
    },
    {
      _id: 'mock17',
      rating: 3,
      title: 'Okay product',
      comment: 'It is good for the price, but could be better. The stitch near the shoulder came off slightly.',
      user: { name: 'Rajesh Kumar' },
      createdAt: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 34,
      dislikes: 5,
      location: 'Patna'
    },
    {
      _id: 'mock18',
      rating: 5,
      title: 'Best in the market!',
      comment: 'Have tried many brands, but Zen-G Wear fits me the best. Will definitely buy more from their collection.',
      user: { name: 'Abhishek Singh' },
      createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 92,
      dislikes: 3,
      location: 'Noida'
    },
    {
      _id: 'mock19',
      rating: 4,
      title: 'Really good',
      comment: 'Comfortable and looks elegant. The delivery was super fast, got it the next day!',
      user: { name: 'Pooja Sharma' },
      createdAt: new Date(Date.now() - 48 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 41,
      dislikes: 0,
      location: 'Surat'
    },
    {
      _id: 'mock20',
      rating: 5,
      title: 'Highly Recommended',
      comment: 'If you are looking for comfort and style, just go for it without a second thought. Totally paisa vasool!',
      user: { name: 'Sanjay Dutt' },
      createdAt: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 110,
      dislikes: 7,
      location: 'Ludhiana'
    },
    {
      _id: 'mock21',
      rating: 5,
      title: 'Awesome',
      comment: 'Nice quality and good packing. Fits perfectly. Thank you.',
      user: { name: 'Mohammad Ali' },
      createdAt: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 14,
      dislikes: 2,
      location: 'Aligarh'
    },
    {
      _id: 'mock22',
      rating: 4,
      title: 'Good purchase',
      comment: 'Overall nice product. Material is soft. Value for money.',
      user: { name: 'Tarun Jain' },
      createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 27,
      dislikes: 1,
      location: 'Udaipur'
    },
    {
      _id: 'mock23',
      rating: 5,
      title: 'Fantastic!',
      comment: 'Loved the fabric and the fit. Excellent quality at this price point.',
      user: { name: 'Divya Nair' },
      createdAt: new Date(Date.now() - 65 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 53,
      dislikes: 4,
      location: 'Thiruvananthapuram'
    },
    {
      _id: 'mock24',
      rating: 5,
      title: 'Just perfect',
      comment: 'Bought this for daily use. Looks very trendy. Fully satisfied.',
      user: { name: 'Vishal Chawla' },
      createdAt: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 38,
      dislikes: 0,
      location: 'Amritsar'
    },
    {
      _id: 'mock25',
      rating: 3,
      title: 'Average',
      comment: 'It is okay for casual wear. Not very premium but decent for the price.',
      user: { name: 'Kishore B' },
      createdAt: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 12,
      dislikes: 8,
      location: 'Madurai'
    },
    {
      _id: 'mock26',
      rating: 5,
      title: 'Superb',
      comment: 'Exactly what I was looking for. Perfect fit and amazing comfort.',
      user: { name: 'Ritu Singh' },
      createdAt: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 64,
      dislikes: 2,
      location: 'Dehradun'
    },
    {
      _id: 'mock27',
      rating: 4,
      title: 'Nice fabric',
      comment: 'The fabric is thick and durable. Good for winter season.',
      user: { name: 'Amitabh R' },
      createdAt: new Date(Date.now() - 85 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 22,
      dislikes: 1,
      location: 'Ranchi'
    },
    {
      _id: 'mock28',
      rating: 5,
      title: 'Excellent product',
      comment: 'Very happy with the purchase. The brand delivers what it promises.',
      user: { name: 'Gaurav K' },
      createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 47,
      dislikes: 3,
      location: 'Guwahati'
    },
    {
      _id: 'mock29',
      rating: 5,
      title: 'Best buy!',
      comment: 'Top quality product. Very comfortable to wear all day long.',
      user: { name: 'Harish M' },
      createdAt: new Date(Date.now() - 95 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 88,
      dislikes: 5,
      location: 'Vadodara'
    },
    {
      _id: 'mock30',
      rating: 4,
      title: 'Good one',
      comment: 'Nice product. Only issue was packaging was a bit torn, otherwise item is perfect.',
      user: { name: 'Shruti P' },
      createdAt: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 16,
      dislikes: 4,
      location: 'Nagpur'
    }
  ];
};
